// Copyright (C) 2019, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

//! Codec round-trip property tests + decode-never-panics smoke (M4.6).
//!
//! Spec: `specs/08-platformvm-pchain.md` §11.1; `specs/02-testing-strategy.md`
//! §4, §6, §8.
//!
//! * `pchain_tx_roundtrip` — `decode(encode(x)) == x` for an arbitrary
//!   [`UnsignedTx`] generated by [`arb_unsigned_tx`], which covers **every**
//!   variant. The generated txs carry arbitrary-but-valid field shapes (they are
//!   not required to pass `syntactic_verify`); they only need to round-trip
//!   through the codec byte-for-byte.
//! * `decode_never_panics` — feeds arbitrary `Vec<u8>` to [`Tx::parse`] and
//!   [`Block::parse`], asserting only that decoding never panics. This is the
//!   stable substitute for the cargo-fuzz `decode_block_tx` target (the repo's
//!   fuzz convention: nightly-only `cargo fuzz`, with a stable proptest smoke as
//!   the always-on gate).

#![allow(
    unused_crate_dependencies,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing
)]

use proptest::collection::vec;
use proptest::prelude::*;

use ava_platformvm::block::Block;
use ava_platformvm::signer::{
    Empty, PUBLIC_KEY_LEN, ProofOfPossession, SIGNATURE_LEN as BLS_SIGNATURE_LEN, Signer,
};
use ava_platformvm::stakeable::{LockIn, LockOut};
use ava_platformvm::txs::components::{
    Auth, BaseTx as AvaxBaseTx, Input, Output, Owner, PChainOwner, TransferableInput,
    TransferableOutput,
};
use ava_platformvm::txs::{
    self, AddAutoRenewedValidatorTx, AddDelegatorTx, AddPermissionlessDelegatorTx,
    AddPermissionlessValidatorTx, AddSubnetValidatorTx, AddValidatorTx, AdvanceTimeTx, BaseTx,
    ConvertSubnetToL1Tx, ConvertSubnetToL1Validator, CreateChainTx, CreateSubnetTx,
    DisableL1ValidatorTx, ExportTx, ImportTx, IncreaseL1ValidatorBalanceTx, RegisterL1ValidatorTx,
    RemoveSubnetValidatorTx, RewardAutoRenewedValidatorTx, RewardValidatorTx,
    SetAutoRenewedValidatorConfigTx, SetL1ValidatorWeightTx, SubnetValidator,
    TransferSubnetOwnershipTx, TransformSubnetTx, Tx, UnsignedTx, Validator,
};
use ava_secp256k1fx::{Input as Secp256k1Input, OutputOwners, TransferInput, TransferOutput};
use ava_types::id::Id;
use ava_types::node_id::NodeId;
use ava_types::short_id::ShortId;

// BLS proof-of-possession signature length (the `register_l1` PoP, which
// reuses `signer::SIGNATURE_LEN` = the BLS signature length, 96 bytes).
const BLS_PROOF_LEN: usize = BLS_SIGNATURE_LEN;

// Bounded collection sizes keep each generated case cheap.
const MAX_VEC: usize = 3;

// ---------------------------------------------------------------------------
// Leaf strategies
// ---------------------------------------------------------------------------

fn arb_id() -> impl Strategy<Value = Id> {
    any::<[u8; 32]>().prop_map(Id::from)
}

fn arb_node_id() -> impl Strategy<Value = NodeId> {
    any::<[u8; 20]>().prop_map(NodeId::from)
}

fn arb_short_id() -> impl Strategy<Value = ShortId> {
    any::<[u8; 20]>().prop_map(ShortId::from)
}

fn arb_bytes() -> impl Strategy<Value = Vec<u8>> {
    vec(any::<u8>(), 0..=8)
}

fn arb_output_owners() -> impl Strategy<Value = OutputOwners> {
    (any::<u64>(), any::<u32>(), vec(arb_short_id(), 0..=MAX_VEC))
        .prop_map(|(locktime, threshold, addrs)| OutputOwners::new(locktime, threshold, addrs))
}

fn arb_owner() -> impl Strategy<Value = Owner> {
    arb_output_owners().prop_map(Owner::Secp256k1)
}

fn arb_transfer_output() -> impl Strategy<Value = TransferOutput> {
    (any::<u64>(), arb_output_owners()).prop_map(|(amt, owners)| TransferOutput::new(amt, owners))
}

fn arb_transfer_input() -> impl Strategy<Value = TransferInput> {
    (any::<u64>(), vec(any::<u32>(), 0..=MAX_VEC))
        .prop_map(|(amt, sig_indices)| TransferInput::new(amt, sig_indices))
}

fn arb_secp_input() -> impl Strategy<Value = Secp256k1Input> {
    vec(any::<u32>(), 0..=MAX_VEC).prop_map(Secp256k1Input::new)
}

fn arb_auth() -> impl Strategy<Value = Auth> {
    arb_secp_input().prop_map(Auth::Secp256k1)
}

// Output interface: secp256k1fx.TransferOutput (7) or stakeable.LockOut (22).
// LockOut wraps a (non-recursive) TransferOutput to keep generation bounded.
fn arb_output() -> impl Strategy<Value = Output> {
    prop_oneof![
        arb_transfer_output().prop_map(Output::Transfer),
        (any::<u64>(), arb_transfer_output()).prop_map(|(locktime, to)| {
            Output::StakeableLock(LockOut::new(locktime, Output::Transfer(to)))
        }),
    ]
}

// Input interface: secp256k1fx.TransferInput (5) or stakeable.LockIn (21).
fn arb_input() -> impl Strategy<Value = Input> {
    prop_oneof![
        arb_transfer_input().prop_map(Input::Transfer),
        (any::<u64>(), arb_transfer_input()).prop_map(|(locktime, ti)| {
            Input::StakeableLock(LockIn::new(locktime, Input::Transfer(ti)))
        }),
    ]
}

fn arb_transferable_output() -> impl Strategy<Value = TransferableOutput> {
    (arb_id(), arb_output()).prop_map(|(asset_id, out)| TransferableOutput { asset_id, out })
}

fn arb_transferable_input() -> impl Strategy<Value = TransferableInput> {
    (arb_id(), any::<u32>(), arb_id(), arb_input()).prop_map(
        |(tx_id, output_index, asset_id, r#in)| TransferableInput {
            tx_id,
            output_index,
            asset_id,
            r#in,
        },
    )
}

fn arb_avax_base_tx() -> impl Strategy<Value = AvaxBaseTx> {
    (
        any::<u32>(),
        arb_id(),
        vec(arb_transferable_output(), 0..=MAX_VEC),
        vec(arb_transferable_input(), 0..=MAX_VEC),
        arb_bytes(),
    )
        .prop_map(|(network_id, blockchain_id, outs, ins, memo)| AvaxBaseTx {
            network_id,
            blockchain_id,
            outs,
            ins,
            memo,
        })
}

fn arb_base_tx() -> impl Strategy<Value = BaseTx> {
    arb_avax_base_tx().prop_map(BaseTx::new)
}

fn arb_validator() -> impl Strategy<Value = Validator> {
    (arb_node_id(), any::<u64>(), any::<u64>(), any::<u64>()).prop_map(
        |(node_id, start, end, wght)| Validator {
            node_id,
            start,
            end,
            wght,
        },
    )
}

fn arb_subnet_validator() -> impl Strategy<Value = SubnetValidator> {
    (arb_validator(), arb_id())
        .prop_map(|(validator, subnet)| SubnetValidator { validator, subnet })
}

fn arb_proof_of_possession() -> impl Strategy<Value = ProofOfPossession> {
    (
        any::<[u8; PUBLIC_KEY_LEN]>(),
        // 96-byte BLS proof; arrays > 32 have no `Arbitrary`, so build from a vec.
        vec(any::<u8>(), BLS_SIGNATURE_LEN..=BLS_SIGNATURE_LEN),
    )
        .prop_map(|(public_key, proof)| {
            let mut sig = [0u8; BLS_SIGNATURE_LEN];
            sig.copy_from_slice(&proof);
            ProofOfPossession::new(public_key, sig)
        })
}

fn arb_signer() -> impl Strategy<Value = Signer> {
    prop_oneof![
        Just(Signer::Empty(Empty)),
        arb_proof_of_possession().prop_map(Signer::ProofOfPossession),
    ]
}

fn arb_bls_proof() -> impl Strategy<Value = [u8; BLS_PROOF_LEN]> {
    vec(any::<u8>(), BLS_PROOF_LEN..=BLS_PROOF_LEN).prop_map(|v| {
        let mut sig = [0u8; BLS_PROOF_LEN];
        sig.copy_from_slice(&v);
        sig
    })
}

fn arb_pchain_owner() -> impl Strategy<Value = PChainOwner> {
    (any::<u32>(), vec(arb_short_id(), 0..=MAX_VEC)).prop_map(|(threshold, addresses)| {
        PChainOwner {
            threshold,
            addresses,
        }
    })
}

// ---------------------------------------------------------------------------
// Per-tx strategies (one per UnsignedTx variant)
// ---------------------------------------------------------------------------

fn arb_add_validator() -> impl Strategy<Value = AddValidatorTx> {
    (
        arb_base_tx(),
        arb_validator(),
        vec(arb_transferable_output(), 0..=MAX_VEC),
        arb_owner(),
        any::<u32>(),
    )
        .prop_map(
            |(base, validator, stake_outs, rewards_owner, delegation_shares)| AddValidatorTx {
                base,
                validator,
                stake_outs,
                rewards_owner,
                delegation_shares,
            },
        )
}

fn arb_add_subnet_validator() -> impl Strategy<Value = AddSubnetValidatorTx> {
    (arb_base_tx(), arb_subnet_validator(), arb_auth()).prop_map(
        |(base, subnet_validator, subnet_auth)| AddSubnetValidatorTx {
            base,
            subnet_validator,
            subnet_auth,
        },
    )
}

fn arb_add_delegator() -> impl Strategy<Value = AddDelegatorTx> {
    (
        arb_base_tx(),
        arb_validator(),
        vec(arb_transferable_output(), 0..=MAX_VEC),
        arb_owner(),
    )
        .prop_map(
            |(base, validator, stake_outs, delegation_rewards_owner)| AddDelegatorTx {
                base,
                validator,
                stake_outs,
                delegation_rewards_owner,
            },
        )
}

fn arb_create_chain() -> impl Strategy<Value = CreateChainTx> {
    (
        arb_base_tx(),
        arb_id(),
        ".{0,8}",
        arb_id(),
        vec(arb_id(), 0..=MAX_VEC),
        arb_bytes(),
        arb_auth(),
    )
        .prop_map(
            |(base, subnet_id, chain_name, vm_id, fx_ids, genesis_data, subnet_auth)| {
                CreateChainTx {
                    base,
                    subnet_id,
                    chain_name,
                    vm_id,
                    fx_ids,
                    genesis_data,
                    subnet_auth,
                }
            },
        )
}

fn arb_create_subnet() -> impl Strategy<Value = CreateSubnetTx> {
    (arb_base_tx(), arb_owner()).prop_map(|(base, owner)| CreateSubnetTx { base, owner })
}

fn arb_import() -> impl Strategy<Value = ImportTx> {
    (
        arb_base_tx(),
        arb_id(),
        vec(arb_transferable_input(), 0..=MAX_VEC),
    )
        .prop_map(|(base, source_chain, imported_inputs)| ImportTx {
            base,
            source_chain,
            imported_inputs,
        })
}

fn arb_export() -> impl Strategy<Value = ExportTx> {
    (
        arb_base_tx(),
        arb_id(),
        vec(arb_transferable_output(), 0..=MAX_VEC),
    )
        .prop_map(|(base, destination_chain, exported_outputs)| ExportTx {
            base,
            destination_chain,
            exported_outputs,
        })
}

fn arb_advance_time() -> impl Strategy<Value = AdvanceTimeTx> {
    any::<u64>().prop_map(|time| AdvanceTimeTx { time })
}

fn arb_reward_validator() -> impl Strategy<Value = RewardValidatorTx> {
    arb_id().prop_map(|tx_id| RewardValidatorTx { tx_id })
}

fn arb_remove_subnet_validator() -> impl Strategy<Value = RemoveSubnetValidatorTx> {
    (arb_base_tx(), arb_node_id(), arb_id(), arb_auth()).prop_map(
        |(base, node_id, subnet, subnet_auth)| RemoveSubnetValidatorTx {
            base,
            node_id,
            subnet,
            subnet_auth,
        },
    )
}

#[allow(clippy::type_complexity)]
fn arb_transform_subnet() -> impl Strategy<Value = TransformSubnetTx> {
    (
        arb_base_tx(),
        arb_id(),
        arb_id(),
        any::<u64>(),
        any::<u64>(),
        any::<u64>(),
        any::<u64>(),
        any::<u64>(),
        any::<u64>(),
        (
            any::<u32>(),
            any::<u32>(),
            any::<u32>(),
            any::<u64>(),
            any::<u8>(),
            any::<u32>(),
            arb_auth(),
        ),
    )
        .prop_map(
            |(
                base,
                subnet,
                asset_id,
                initial_supply,
                maximum_supply,
                min_consumption_rate,
                max_consumption_rate,
                min_validator_stake,
                max_validator_stake,
                (
                    min_stake_duration,
                    max_stake_duration,
                    min_delegation_fee,
                    min_delegator_stake,
                    max_validator_weight_factor,
                    uptime_requirement,
                    subnet_auth,
                ),
            )| TransformSubnetTx {
                base,
                subnet,
                asset_id,
                initial_supply,
                maximum_supply,
                min_consumption_rate,
                max_consumption_rate,
                min_validator_stake,
                max_validator_stake,
                min_stake_duration,
                max_stake_duration,
                min_delegation_fee,
                min_delegator_stake,
                max_validator_weight_factor,
                uptime_requirement,
                subnet_auth,
            },
        )
}

fn arb_add_permissionless_validator() -> impl Strategy<Value = AddPermissionlessValidatorTx> {
    (
        arb_base_tx(),
        arb_validator(),
        arb_id(),
        arb_signer(),
        vec(arb_transferable_output(), 0..=MAX_VEC),
        arb_owner(),
        arb_owner(),
        any::<u32>(),
    )
        .prop_map(
            |(
                base,
                validator,
                subnet,
                signer,
                stake_outs,
                validator_rewards_owner,
                delegator_rewards_owner,
                delegation_shares,
            )| AddPermissionlessValidatorTx {
                base,
                validator,
                subnet,
                signer,
                stake_outs,
                validator_rewards_owner,
                delegator_rewards_owner,
                delegation_shares,
                verified: std::cell::OnceCell::new(),
            },
        )
}

fn arb_add_permissionless_delegator() -> impl Strategy<Value = AddPermissionlessDelegatorTx> {
    (
        arb_base_tx(),
        arb_validator(),
        arb_id(),
        vec(arb_transferable_output(), 0..=MAX_VEC),
        arb_owner(),
    )
        .prop_map(
            |(base, validator, subnet, stake_outs, delegation_rewards_owner)| {
                AddPermissionlessDelegatorTx {
                    base,
                    validator,
                    subnet,
                    stake_outs,
                    delegation_rewards_owner,
                }
            },
        )
}

fn arb_transfer_subnet_ownership() -> impl Strategy<Value = TransferSubnetOwnershipTx> {
    (arb_base_tx(), arb_id(), arb_auth(), arb_owner()).prop_map(
        |(base, subnet, subnet_auth, owner)| TransferSubnetOwnershipTx {
            base,
            subnet,
            subnet_auth,
            owner,
        },
    )
}

fn arb_base() -> impl Strategy<Value = BaseTx> {
    arb_base_tx()
}

fn arb_convert_subnet_validator() -> impl Strategy<Value = ConvertSubnetToL1Validator> {
    (
        arb_bytes(),
        any::<u64>(),
        any::<u64>(),
        arb_proof_of_possession(),
        arb_pchain_owner(),
        arb_pchain_owner(),
    )
        .prop_map(
            |(node_id, weight, balance, signer, remaining_balance_owner, deactivation_owner)| {
                ConvertSubnetToL1Validator {
                    node_id,
                    weight,
                    balance,
                    signer,
                    remaining_balance_owner,
                    deactivation_owner,
                }
            },
        )
}

fn arb_convert_subnet_to_l1() -> impl Strategy<Value = ConvertSubnetToL1Tx> {
    (
        arb_base_tx(),
        arb_id(),
        arb_id(),
        arb_bytes(),
        vec(arb_convert_subnet_validator(), 0..=MAX_VEC),
        arb_auth(),
    )
        .prop_map(
            |(base, subnet, chain_id, address, validators, subnet_auth)| ConvertSubnetToL1Tx {
                base,
                subnet,
                chain_id,
                address,
                validators,
                subnet_auth,
            },
        )
}

fn arb_register_l1_validator() -> impl Strategy<Value = RegisterL1ValidatorTx> {
    (arb_base_tx(), any::<u64>(), arb_bls_proof(), arb_bytes()).prop_map(
        |(base, balance, proof_of_possession, message)| RegisterL1ValidatorTx {
            base,
            balance,
            proof_of_possession,
            message,
        },
    )
}

fn arb_set_l1_validator_weight() -> impl Strategy<Value = SetL1ValidatorWeightTx> {
    (arb_base_tx(), arb_bytes())
        .prop_map(|(base, message)| SetL1ValidatorWeightTx { base, message })
}

fn arb_increase_l1_validator_balance() -> impl Strategy<Value = IncreaseL1ValidatorBalanceTx> {
    (arb_base_tx(), arb_id(), any::<u64>()).prop_map(|(base, validation_id, balance)| {
        IncreaseL1ValidatorBalanceTx {
            base,
            validation_id,
            balance,
        }
    })
}

fn arb_disable_l1_validator() -> impl Strategy<Value = DisableL1ValidatorTx> {
    (arb_base_tx(), arb_id(), arb_auth()).prop_map(|(base, validation_id, disable_auth)| {
        DisableL1ValidatorTx {
            base,
            validation_id,
            disable_auth,
        }
    })
}

#[allow(clippy::type_complexity)]
fn arb_add_auto_renewed_validator() -> impl Strategy<Value = AddAutoRenewedValidatorTx> {
    (
        arb_base_tx(),
        arb_bytes(),
        arb_signer(),
        vec(arb_transferable_output(), 0..=MAX_VEC),
        arb_owner(),
        arb_owner(),
        arb_owner(),
        (any::<u32>(), any::<u32>(), any::<u64>()),
    )
        .prop_map(
            |(
                base,
                validator_node_id,
                signer,
                stake_outs,
                validator_rewards_owner,
                delegator_rewards_owner,
                validator_authority,
                (delegation_shares, auto_compound_reward_shares, period),
            )| AddAutoRenewedValidatorTx {
                base,
                validator_node_id,
                signer,
                stake_outs,
                validator_rewards_owner,
                delegator_rewards_owner,
                validator_authority,
                delegation_shares,
                auto_compound_reward_shares,
                period,
            },
        )
}

fn arb_set_auto_renewed_validator_config() -> impl Strategy<Value = SetAutoRenewedValidatorConfigTx>
{
    (
        arb_base_tx(),
        arb_id(),
        arb_auth(),
        any::<u32>(),
        any::<u64>(),
    )
        .prop_map(|(base, tx_id, auth, auto_compound_reward_shares, period)| {
            SetAutoRenewedValidatorConfigTx {
                base,
                tx_id,
                auth,
                auto_compound_reward_shares,
                period,
            }
        })
}

fn arb_reward_auto_renewed_validator() -> impl Strategy<Value = RewardAutoRenewedValidatorTx> {
    (arb_id(), any::<u64>())
        .prop_map(|(tx_id, timestamp)| RewardAutoRenewedValidatorTx { tx_id, timestamp })
}

// ---------------------------------------------------------------------------
// The UnsignedTx union strategy — covers EVERY variant.
// ---------------------------------------------------------------------------

/// A proptest [`Strategy`] generating every [`UnsignedTx`] variant with
/// arbitrary-but-valid field shapes. The result only needs to round-trip through
/// the codec; it is **not** required to pass `syntactic_verify`.
fn arb_unsigned_tx() -> impl Strategy<Value = UnsignedTx> {
    // `prop_oneof!` is limited in arity, so the variants are split into two
    // groups and unioned. Every variant of `UnsignedTx` appears exactly once.
    let group_a = prop_oneof![
        arb_add_validator().prop_map(UnsignedTx::AddValidator),
        arb_add_subnet_validator().prop_map(UnsignedTx::AddSubnetValidator),
        arb_add_delegator().prop_map(UnsignedTx::AddDelegator),
        arb_create_chain().prop_map(UnsignedTx::CreateChain),
        arb_create_subnet().prop_map(UnsignedTx::CreateSubnet),
        arb_import().prop_map(UnsignedTx::Import),
        arb_export().prop_map(UnsignedTx::Export),
        arb_advance_time().prop_map(UnsignedTx::AdvanceTime),
        arb_reward_validator().prop_map(UnsignedTx::RewardValidator),
        arb_remove_subnet_validator().prop_map(UnsignedTx::RemoveSubnetValidator),
        arb_transform_subnet().prop_map(UnsignedTx::TransformSubnet),
        arb_add_permissionless_validator().prop_map(UnsignedTx::AddPermissionlessValidator),
    ];
    let group_b = prop_oneof![
        arb_add_permissionless_delegator().prop_map(UnsignedTx::AddPermissionlessDelegator),
        arb_transfer_subnet_ownership().prop_map(UnsignedTx::TransferSubnetOwnership),
        arb_base().prop_map(UnsignedTx::Base),
        arb_convert_subnet_to_l1().prop_map(UnsignedTx::ConvertSubnetToL1),
        arb_register_l1_validator().prop_map(UnsignedTx::RegisterL1Validator),
        arb_set_l1_validator_weight().prop_map(UnsignedTx::SetL1ValidatorWeight),
        arb_increase_l1_validator_balance().prop_map(UnsignedTx::IncreaseL1ValidatorBalance),
        arb_disable_l1_validator().prop_map(UnsignedTx::DisableL1Validator),
        arb_add_auto_renewed_validator().prop_map(UnsignedTx::AddAutoRenewedValidator),
        arb_set_auto_renewed_validator_config().prop_map(UnsignedTx::SetAutoRenewedValidatorConfig),
        arb_reward_auto_renewed_validator().prop_map(UnsignedTx::RewardAutoRenewedValidator),
    ];
    prop_oneof![group_a, group_b]
}

proptest! {
    // The plan calls for 4096 cases; 1024 keeps CI fast while still exercising
    // every variant many times over (`prop::pchain_tx_roundtrip`).
    #![proptest_config(ProptestConfig::with_cases(1024))]

    /// `decode(encode(x)) == x` for an arbitrary [`UnsignedTx`] (every variant).
    #[test]
    fn pchain_tx_roundtrip(unsigned in arb_unsigned_tx()) {
        let c = txs::codec::codec().expect("build codec");
        let encoded = c
            .marshal(ava_platformvm::CODEC_VERSION, &unsigned)
            .expect("marshal");

        let mut decoded = UnsignedTx::default();
        c.unmarshal(&encoded, &mut decoded).expect("unmarshal");
        prop_assert_eq!(&decoded, &unsigned, "decode(encode(x)) == x");

        // Byte-stability: re-encoding the decoded value reproduces the bytes.
        let reencoded = c
            .marshal(ava_platformvm::CODEC_VERSION, &decoded)
            .expect("re-marshal");
        prop_assert_eq!(reencoded, encoded, "encode(decode(encode(x))) == encode(x)");
    }

    /// A signed [`Tx`] (unsigned body, no creds) also round-trips through
    /// `Tx::initialize`/`Tx::parse`.
    #[test]
    fn pchain_signed_tx_roundtrip(unsigned in arb_unsigned_tx()) {
        let c = txs::codec::codec().expect("build codec");
        let mut tx = Tx::new(unsigned);
        tx.initialize(&c).expect("initialize");
        let parsed = Tx::parse(&c, tx.bytes()).expect("parse");
        prop_assert_eq!(&parsed.unsigned, &tx.unsigned, "signed tx round-trip");
        prop_assert_eq!(parsed.id(), tx.id(), "tx_id round-trip");
    }

    /// Decode-never-panics: arbitrary bytes through the signed-tx and block
    /// parsers never panic (errors are expected and ignored). This is the stable
    /// substitute for the cargo-fuzz `decode_block_tx` target (`specs/02` §8).
    #[test]
    fn decode_never_panics(data in vec(any::<u8>(), 0..=512)) {
        let _ = Tx::parse(txs::Codec(), &data);
        let _ = Block::parse(txs::Codec(), &data);
    }
}
