// Copyright (C) 2019, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

//! Stable-toolchain smoke harness mirroring the nightly `cargo-fuzz` targets
//! (M1.25, spec 02 §8). The fuzz targets in `crates/ava-merkledb/fuzz` require a
//! nightly compiler + LLVM sanitizers, so they cannot run on the pinned stable
//! nix shell. These proptests exercise the **same** shared
//! [`ava_merkledb::fuzz_support`] logic via proptest-generated bytes fed through
//! `arbitrary`, so the no-panic / oracle-agreement invariants are gated on every
//! `cargo nextest` run today.
//!
//! Requires the `fuzzing` feature (the verification gate runs `--all-features`).

#![cfg(feature = "fuzzing")]

use arbitrary::{Arbitrary, Unstructured};
use proptest::collection::vec;
use proptest::prelude::*;

use ava_merkledb::fuzz_support::{DbOp, run_node_codec, run_op_stream};

proptest! {
    /// The same op-stream-vs-`BTreeMap`-oracle check as the `op_stream` fuzz
    /// target, driven by `arbitrary` over proptest-generated bytes. No panic,
    /// no over-read, oracle always agrees.
    #[test]
    fn fuzz_op_stream_smoke(data in vec(any::<u8>(), 0..512)) {
        let mut u = Unstructured::new(&data);
        // Decoding the op stream out of arbitrary bytes must itself not panic;
        // an exhausted-input error simply yields a shorter stream.
        if let Ok(ops) = Vec::<DbOp>::arbitrary(&mut u) {
            run_op_stream(&ops);
        }
    }

    /// The same `decode_db_node`-never-panics check as the `node_codec` fuzz
    /// target (spec §8 "decoding never panics").
    #[test]
    fn node_codec_never_panics(data in vec(any::<u8>(), 0..256)) {
        run_node_codec(&data);
    }
}
