// Copyright (C) 2019, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

//! `golden::flag_parity` — the per-PR M8.4 exit gate (specs 13 §25, 12 §1.8).
//!
//! Diffs the generated Rust flag catalog (`FLAG_SPECS` / `build_command`)
//! against the committed Go `config.BuildFlagSet()` snapshot
//! (`tests/vectors/config/flags.json`, regenerated by `cargo xtask gen-flags`).
//! Asserts (a) set-equality of names, (b) per-flag pflag type equality,
//! (c) per-flag default-string equality, (d) deprecated set + message equality.

#![allow(unused_crate_dependencies)]

use std::collections::BTreeMap;

use ava_config::duration::{format_go_duration, parse_go_duration};
use ava_config::flags::{FLAG_SPECS, FlagKind, build_command};

/// One snapshot record (the shape the Go emitter writes, sorted by name).
#[derive(Debug, Clone, PartialEq, Eq, serde::Deserialize)]
struct FlagRecord {
    name: String,
    #[serde(rename = "type")]
    type_str: String,
    default: String,
    deprecated: bool,
    deprecation_msg: String,
}

/// The committed snapshot: provenance header + sorted records.
#[derive(Debug, serde::Deserialize)]
struct FlagSnapshot {
    #[serde(rename = "_provenance")]
    provenance: BTreeMap<String, String>,
    flags: Vec<FlagRecord>,
}

/// Host-dependent defaults pinned to symbolic forms on BOTH sides
/// (13 §25 step 1): `fd-limit` is OS-dependent, the CPU-throttler trio is
/// `runtime.NumCPU()`-derived. Must match the Go emitter's table.
fn symbolic_default(name: &str) -> Option<&'static str> {
    match name {
        "fd-limit" => Some("DefaultFDLimit"),
        "throttler-inbound-cpu-validator-alloc" => Some("NumCPU"),
        "throttler-inbound-cpu-max-non-validator-usage" => Some("0.8*NumCPU"),
        "throttler-inbound-cpu-max-non-validator-node-usage" => Some("NumCPU/8"),
        _ => None,
    }
}

/// Normalizes a pflag `duration` DefValue to Go's `Duration.String()` form so
/// the comparison is insensitive to spelling (`"5m"` vs `"5m0s"`).
fn normalize_duration(name: &str, raw: &str) -> String {
    let parsed =
        parse_go_duration(raw).unwrap_or_else(|e| panic!("{name}: bad duration {raw:?}: {e}"));
    format_go_duration(parsed)
}

/// Serializes the Rust flag table into the snapshot record shape.
fn rust_records() -> Vec<FlagRecord> {
    FLAG_SPECS
        .iter()
        .map(|s| {
            let default = if let Some(sym) = symbolic_default(s.key) {
                sym.to_string()
            } else if s.kind == FlagKind::Duration {
                normalize_duration(s.key, &s.default.resolve())
            } else {
                s.default.resolve()
            };
            FlagRecord {
                name: s.key.to_string(),
                type_str: s.kind.go_type_str().to_string(),
                default,
                deprecated: s.deprecated.is_some(),
                deprecation_msg: s.deprecated.unwrap_or("").to_string(),
            }
        })
        .collect()
}

#[test]
fn flag_parity() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/config/flags.json"
    );
    let raw = std::fs::read_to_string(path).unwrap_or_else(|e| {
        panic!("missing Go snapshot {path} (run `cargo xtask gen-flags`): {e}")
    });
    let snap: FlagSnapshot = serde_json::from_str(&raw).expect("parse flags.json");
    assert!(
        snap.provenance.contains_key("go_commit"),
        "snapshot must carry its provenance header"
    );

    // The clap command must build (panics on duplicate/invalid args) and carry
    // one user arg per spec (+ clap's auto `--help`).
    let mut cmd = build_command(FLAG_SPECS);
    cmd.build();
    let num_args = cmd.get_arguments().filter(|a| a.get_id() != "help").count();
    assert_eq!(num_args, FLAG_SPECS.len(), "clap arg count");

    let go: BTreeMap<String, FlagRecord> = snap
        .flags
        .iter()
        .map(|r| {
            let mut r = r.clone();
            if r.type_str == "duration" {
                r.default = normalize_duration(&r.name, &r.default);
            }
            (r.name.clone(), r)
        })
        .collect();
    let rust: BTreeMap<String, FlagRecord> = rust_records()
        .into_iter()
        .map(|r| (r.name.clone(), r))
        .collect();

    // (a) Set-equality of names (catches added/removed/renamed flags).
    let only_go: Vec<&String> = go.keys().filter(|k| !rust.contains_key(*k)).collect();
    let only_rust: Vec<&String> = rust.keys().filter(|k| !go.contains_key(*k)).collect();
    assert!(
        only_go.is_empty() && only_rust.is_empty(),
        "flag-name drift — only in Go: {only_go:?}; only in Rust: {only_rust:?}"
    );

    // (b) type, (c) default, (d) deprecation — per flag, with a full diff list.
    let mut diffs = Vec::new();
    for (name, g) in &go {
        let r = rust.get(name).expect("name sets already proven equal");
        if g != r {
            diffs.push(format!("{name}:\n  go:   {g:?}\n  rust: {r:?}"));
        }
    }
    assert!(
        diffs.is_empty(),
        "{} flag record(s) drifted:\n{}",
        diffs.len(),
        diffs.join("\n")
    );
}
